Allow change of serializer from 'json' to something else.
CESNET/perun-mitreid pull request #148
Opened 2020-11-04 14:54 UTC by pavolpluta

2020-11-05 11:41 UTC, vyskocilpavel approved these changes

2020-11-09 12:36 UTC, dBucik requested changes

2020-11-09 12:36 UTC, dBucik commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/PerunConnectorRpc.java
> +		if (serializer == null || serializer.trim().isEmpty()) {
Use StringUtils.hasText from Spring instead. If the parameter is null or empty, use `json` as the default value rather than throwing an exception.

2020-11-09 12:36 UTC, dBucik reviewed
Please add this change to changelog as well.

2020-11-09 13:50 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/PerunConnectorRpc.java
> +		}
@dBucik 
Is this code of block required?

The default serializer is configured in user-context.xml, isn't it?

2020-11-11 10:27 UTC, dBucik approved these changes

2020-11-11 10:27 UTC, merged