Logs refactoring
CESNET/perun-mitreid pull request #160
Opened 2021-01-25 14:43 UTC by pavolpluta

### Components being refactored: 
- server/claims/sources
- server/filters + server/filters/impl

### Logs changes:
- More logs
- More apparent logs
- Grammar fixes
- First letters capitalized (“Title case”)
- Unified structure for the whole component
- Added logs to classes without logs

### Questions:
- **ExtractValuesByDomainSource:** Are lines 53-55 necessary, if the check is done in the constructor?

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EdupersonScopedAffiliationsMUSource.java
> +		log.debug("Initializing EPSA_MU claim source");
And I think that trace is a better choice than debug for this log msg.

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EdupersonScopedAffiliationsMUSource.java
> +			log.error("Cannot read EPSA_MU config file", ex);
The same as above. Use Class name

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EdupersonScopedAffiliationsMUSource.java
> +					log.debug("Added affiliation: {}", affiliation);
Trace instead of debug.

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EdupersonScopedAffiliationsMUSource.java
> +			log.debug("Added affiliation: {}", affiliation);
Trace instead of debug.

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EdupersonScopedAffiliationsMUSource.java
> +		log.debug("Producing values started for user {} with sub: {}", userId, pctx.getSub());
Add information about which attribute values will be produced. 

I think that can be trace instead of debug.

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EdupersonScopedAffiliationsMUSource.java
> +		log.debug("Value {} for user {} with sub {} produced", result, userId, pctx.getSub());
Add information about which attribute values will be produced.

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/CallPerunFiltersFilter.java
>                  log.debug("Calling filter: {}", filter.getClass().getName());
missing `'{}'`

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/FiltersUtils.java
> +			log.warn("ClientName is null or empty, skipping to the next filter");
Maybe add information about clientId

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/FiltersUtils.java
> +		log.debug("Returning requestMap: {}", requestMap);
Should be trace and I think that will be good to know from which code we get this log msg.

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/FiltersUtils.java
> +		log.debug("Fetching Perun user with extLogin '{}' and extSourceName '{}'", principal.getExtLogin(), principal.getExtSourceName());
Should be trace

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/FiltersUtils.java
> +		log.debug("Looking for perunUser...");
Should be trace

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/FiltersUtils.java
> +		log.debug("Redirecting user to the registration form...");
Please log this msg after line 290 and add the information about refirectUrl

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunAuthenticationFilter.java
> +		log.debug("PerunAuthentication filter called");
TRACE

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunAuthenticationFilter.java
> +				log.debug("User is logged in, no principal found");
Please add "User is redirecting to Unapproved page"

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/ProxyStatisticsFilter.java
> +			log.debug("Extracted spId: {}", spId);
TRACE if it is required

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/ProxyStatisticsFilter.java
> +			log.debug("Extracted idpId: {}", idpId);
TRACE if it is required

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/ProxyStatisticsFilter.java
> +		log.info("User identity: {},\nservice: {},\nserviceName: {},\nvia IdP: {}", perunPrincipal.getExtLogin(),
Don't use newlines. The log format is used for parsing in rsyslog.

2021-01-26 11:41 UTC, vyskocilpavel commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/ValidUserFilter.java
> +			log.debug("User: {},\nallEnvVos: {},\nallEnvGroups: {},\nadditionalVos: {},\nadditionalGroups: {}",
Don't use newline

2021-01-26 13:59 UTC, dBucik requested changes
We should have in place a discussion about some things and our overall vision of such changes.

2021-01-26 13:59 UTC, dBucik commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/ExtractValuesByDomainSource.java
> +				log.debug("Attribute value for '{}' in domain '{}' found", attributeName, domain);
This message leaves me confused - I do not know what is the attributeName, what is the domain and suddenly there is some mention of the attribute value. What are you trying to capture here?

2021-01-26 13:59 UTC, dBucik commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EntitlementSource.java
> +				log.trace("Added forwarded entitlement: {}", entitlement);
This is a great example where TRACE is the better choice than DEBUG. (No need to do anything, just a comment).

2021-01-26 13:59 UTC, dBucik commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EntitlementSource.java
> +			log.trace("Added group name entitlement: {}", gNameEntitlement);
Could you swap these two lines to keep consistent that we get the thing, log message and add it afterwards?

2021-01-26 13:59 UTC, dBucik commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/ExtractValuesByDomainSource.java
> +				log.debug("Found subvalues for domain '{}': {}", domain, result);
Same  as above.

2021-01-26 13:59 UTC, dBucik commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/CallPerunFiltersFilter.java
>                  log.debug("Calling filter: {}", filter.getClass().getName());
Do you mean the quotes?

2021-01-26 13:59 UTC, dBucik commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunFiltersContext.java
> +			log.info("Loaded filter class '{}' for '{}'", filter.getClass().getSimpleName(), filterName);
Just using the word "for" does not seem correct to me. The second parameter passed is the actual name under which the filter is identified in the configuration. I would probably use something like "for filter named XYZ"

2021-01-26 13:59 UTC, dBucik commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunFiltersContext.java
> +			log.error("Filter class '{}' not found", filterClass);
Add name of the filter from configuration (filterName)

2021-01-26 13:59 UTC, dBucik commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunFiltersContext.java
> +			log.error("Filter class '{}' does not have proper constructor", filterClass);
Add name of the filter from configuration (filterName)

2021-01-26 13:59 UTC, dBucik commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunFiltersContext.java
> +			log.error("Filter class '{}' cannot be instantiated", filterClass, e);
Add name of the filter from configuration (filterName)

2021-01-26 13:59 UTC, dBucik commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunRequestFilter.java
> +            log.debug("Filter '{}' has been skipped, did not match/authorize the request", filterName);
Do not remove the space before _/authorize_, wrap it as well in the quotes.

2021-01-26 13:59 UTC, dBucik commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunRequestFilter.java
> +            log.debug("Skipping filter '{}' because of sub '{}'", filterName, sub);
Perhaps modify this message to better explained that it has been configured to skip this filter if the user identifier is == specified sub.

2021-01-26 13:59 UTC, dBucik commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunRequestFilter.java
> +            log.debug("Skipping filter '{}' because of client_id '{}'", filterName, clientId);
Perhaps modify this message to better explained that it has been configured to skip this filter if the service identifier is == specified client_id.

2021-01-27 12:59 UTC, pavolpluta commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EdupersonScopedAffiliationsMUSource.java
> +		log.debug("Producing values started for user {} with sub: {}", userId, pctx.getSub());
Log with the produced attr value is on the line 101. I will change this whole line because it is pretty much duplicate with that log on the line 101.

2021-01-27 13:01 UTC, pavolpluta commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EdupersonScopedAffiliationsMUSource.java
> +		log.debug("Value {} for user {} with sub {} produced", result, userId, pctx.getSub());
What information? Result of the variable 'result' is already being printed

2021-01-27 13:05 UTC, pavolpluta commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/CallPerunFiltersFilter.java
>                  log.debug("Calling filter: {}", filter.getClass().getName());
That is on purpose - I use either `: {}` (mainly at the end of the line) or `'{}'` for printing the variables inside the text, but not both, as I find it unnecessarily over-complicated.

2021-01-27 13:09 UTC, pavolpluta commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunAuthenticationFilter.java
> +				log.debug("User is logged in, no principal found");
This log is already included at the start of the `redirectUnapproved` method

2021-01-27 13:49 UTC, pavolpluta commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/ExtractValuesByDomainSource.java
>  public class ExtractValuesByDomainSource extends ClaimSource {
Okay, can you tell me how to obtain the scope inside these classes? Thanks

2021-01-27 13:59 UTC, pavolpluta commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/ExtractValuesByDomainSource.java
> +				log.debug("Attribute value for '{}' in domain '{}' found", attributeName, domain);
I just wanted to distinguish whether textual or array attr value is returned as there are two possible paths in the method. I'll make the log more clear, also providing attr name.

2021-01-27 14:11 UTC, pavolpluta commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/FiltersUtils.java
> +		log.debug("Returning requestMap: {}", requestMap);
What do you mean by 'from which code'? You want to add to the log that the code is called from the FiltersUtils class?

2021-01-27 14:18 UTC, pavolpluta commented on oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/ExtractValuesByDomainSource.java
> +				log.debug("Found subvalues for domain '{}': {}", domain, result);
I don't exactly know how and what should and what should not be logged. I made it a bit more clear now. If it still doesn't make sense, I can remove all the logs from this method then. Just check it please.

2021-02-05 05:56 UTC, merged